package com.model.pojo;
// Generated Oct 26, 2020 11:10:05 AM by Hibernate Tools 4.3.1



/**
 * Diarylike generated by hbm2java
 */
public class Diarylike  implements java.io.Serializable {


     private Integer id;
     private Diary diary;
     private User user;

    public Diarylike() {
    }

    public Diarylike(Diary diary, User user) {
       this.diary = diary;
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Diary getDiary() {
        return this.diary;
    }
    
    public void setDiary(Diary diary) {
        this.diary = diary;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


