package com.model.pojo;
// Generated Oct 26, 2020 11:10:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Diary generated by hbm2java
 */
public class Diary  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String title;
     private String text;
     private Date date;
     private Set<Diarylike> diarylikes = new HashSet<Diarylike>(0);

    public Diary() {
    }

	
    public Diary(User user, String title, String text, Date date) {
        this.user = user;
        this.title = title;
        this.text = text;
        this.date = date;
    }
    public Diary(User user, String title, String text, Date date, Set<Diarylike> diarylikes) {
       this.user = user;
       this.title = title;
       this.text = text;
       this.date = date;
       this.diarylikes = diarylikes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Diarylike> getDiarylikes() {
        return this.diarylikes;
    }
    
    public void setDiarylikes(Set<Diarylike> diarylikes) {
        this.diarylikes = diarylikes;
    }




}


